### ISSUE TITLE
Normalization will generate nan if 

### ISSUE THREAD

**Issue by rafaelvalle** [craffel/midi-dataset#13]
[this code](https://github.com/craffel/midi-dataset/blob/604a255ba2ecbb74984b5b507923f9a8b29e2136/scripts/align_text_matches.py#L206)
```
         score /= distance_matrix[
            aligned_midi_indices.min():aligned_midi_indices.max(),
            aligned_audio_indices.min():aligned_audio_indices.max()].mean()
```
Will produce a _nan_ when `len(aligned_midi_indices) == 1 or len(aligned_audio_indices) == 1`

**Comment by craffel** [comment]
Yes, it will also produce `nan` when the mean of the distance matrix submatrix spanned by the alignment path is zero.  These are all degenerate cases in my mind, so `nan` is appropriate.  Do you disagree?

**Comment by rafaelvalle** [comment]
MIDI or Audio files of length 1 are most likely degenerate.
However, this routine could be used to compare beat synchronized CQTs, in which case beat comparisons including beats of length 1 is not degenerate. In this case, would you say it is not appropriate, degenerate, to normalize the score by the mean of the distance vector (distance matrix with a single row...)?

**Comment by craffel** [comment]
> However, this routine could be used to compare beat synchronized CQTs, in which case beat comparisons including beats of length 1 is not degenerate.

Well, that depends on whether you believe any pieces of music have a single "beat" :).  Either way, though, if you are comparing a single vector to a sequence of vectors you shouldn't be using DTW, you can just find the argmin of the pairwise distances.

At any rate, looking at this more closely I think it makes more sense (and importantly is safe) to actually normalize by 
```Python
distance_matrix[aligned_midi_indices.min():aligned_midi_indices.max() + 1,
                aligned_audio_indices.min():aligned_audio_indices.max() + 1].mean()
```
because these are lists of indices.  This should solve your problem.  I will think about this more and may change it eventually.

**Comment by rafaelvalle** [comment]
Will look at the outlier literature for single beat pieces! 👍  
I'm doing clustering on representatives segments of a song. Some of these segments actually are one beat long.

Exactly, argmin of the pairwise distances, but the code looks cleaner without the if clase for this exception :)

Yep, this also solves the problem. I just wanted to let you know about it!
Be well!
